apiVersion: flux-framework.org/v1alpha2
kind: MetricSet
metadata:
  labels:
    app.kubernetes.io/name: metricset
    app.kubernetes.io/instance: metricset-sample
  name: metricset-sample
spec:
  # Number of pods for lammps (one launcher, the rest workers)
  pods: 4
  logging:
    interactive: true

  metrics:

   # Running more scaled lammps is our main goal
   - name: app-lammps

     # This flux addon is built on rocky, and we can provide additional os bases
     image: ghcr.io/converged-computing/metric-lammps-intel-mpi:rocky

     options:
       command: lmp -v x 2 -v y 2 -v z 2 -in in.reaxc.hns -nocite
       workdir: /opt/lammps/examples/reaxff/HNS

     # Add on hpctoolkit, will mount a volume and wrap lammps
     addons:
       - name: workload-flux
         options:
           # Needed for intel MPI I think?
           preCommand: |
             export PMI_TRACE=0xff
             # export I_MPI_PMI_LIBRARY=/opt/intel/mpi/latest/lib/libmpicxx.so
             export I_MPI_PMI_LIBRARY=${fluxroot}/lib/flux/libpmi.so

           # optionFlags: -ompi=pmix
           # Ensure library path (with MPI) is used first
           libraryPath: /opt/intel/mpi/latest/lib
           # Ensure the working directory is consistent
           workdir: /opt/lammps/examples/reaxff/HNS