# permissions for end users to edit metricsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: metricset-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: test
    app.kubernetes.io/part-of: test
    app.kubernetes.io/managed-by: kustomize
  name: metricset-editor-role
rules:
- apiGroups:
  - flux-framework.org
  resources:
  - metricsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flux-framework.org
  resources:
  - metricsets/status
  verbs:
  - get
