apiVersion: flux-framework.org/v1alpha2
kind: MetricSet
metadata:
  labels:
    app.kubernetes.io/name: metricset
    app.kubernetes.io/instance: metricset-sample
  name: metricset-sample
spec:
  # Number of pods for lammps (one launcher, the rest workers)
  pods: 4
  metrics:
   - name: app-lammps
     image: ghcr.io/converged-computing/metric-lammps-intel-mpi:rocky
     addons:
       - name: commands
         options:
           preBlock: dnf install perf -y && sleep infinity
           prefix: /opt/intel/mpi/2021.8.0/bin/mpirun --hostfile ./hostlist.txt -np 2 --map-by socket perf stat
           suffix: sleep infinity
