apiVersion: flux-framework.org/v1alpha1
kind: MetricSet
metadata:
  labels:
    app.kubernetes.io/name: metricset
    app.kubernetes.io/instance: metricset-sample
  name: metricset-sample
spec:
  application:
    image: ubuntu
    command: sleep 10
  metrics:

    # Higher sampling for more data to plot :)
    - name: perf-sysstat
      rate: 2